---
- name: install docker on remote nodes
  hosts: remote
  user: ubuntu
  become: yes

  roles:
  - docker
  
- name: install docker on remote nodes
  hosts: remote_centos
  user: centos
  become: yes

  roles:
  - docker
